name: Deploy Policies
on:
  push:
    branches:
      - dev
      - 'ttrs-*'
  pull_request:
    types: [closed]
    branches:
      - nonprod
      - main
      - prod
  workflow_dispatch:
    inputs:
      environment:
        description: Environment (dev, nonprod, main, prod)
        required: true
        type: string
      python_version:
        description: Python version
        required: true
        type: string
      aws_region:
        description: AWS region
        required: true
        type: string
      bucket_name:
        description: S3 bucket name
        required: true
        type: string
      table_name:
        description: DynamoDB table name
        required: true
        type: string
      lambda_function_name:
        description: Lambda function name
        required: true
        type: string
permissions:
  id-token: write
  contents: write
  actions: write
jobs:
  DeployPolicies:
    runs-on: default
    strategy:
      matrix:
        environment: [dev, nonprod, main, prod]
      max-parallel: 1
    environment: ${{ matrix.environment }}
    if: |
      (matrix.environment == 'dev' && github.event_name == 'push' && (github.ref_name == 'dev' || startsWith(github.ref_name, 'ttrs-'))) ||
      (matrix.environment == 'nonprod' && github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'nonprod' && github.event.pull_request.head.ref == 'dev') ||
      (matrix.environment == 'main' && github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'nonprod') ||
      (matrix.environment == 'prod' && github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod' && github.event.pull_request.head.ref == 'main') ||
      (github.event_name == 'workflow_dispatch' && inputs.environment == matrix.environment)
    steps:
      - name: Setup Environment
        uses: ./.github/actions/deploy
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          gha-trust-role: ${{ vars.GHA_TRUST_ROLE }}
          gha-cicd-role: ${{ vars.GHA_CICD_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Update Policies
        uses: ./.github/actions/update-policies
        with:
          aws-region: ${{ vars.AWS_REGION }}
          bucket-name: ${{ vars.BUCKET_NAME }}
          table-name: ${{ vars.TABLE_NAME }}
          lambda-function-name: ${{ vars.LAMBDA_FUNCTION_NAME }}
