AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Lambda function to update prp-db-org-policy DynamoDB table with policies from aws-guardrail-policy-security repo.

Parameters:
  TableName:
    Type: String
    Default: prp-db-org-policy
    Description: Name of the DynamoDB table to store policies.
  BucketName:
    Type: String
    Default: grd-pol
    Description: Name of the S3 bucket to store policy files (must be 3-63 characters).

Resources:
  PolicyUpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GuardrailPolicyUpdate
      Handler: index.handler
      Runtime: python3.11
      Timeout: 300
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib.parse
          from decimal import Decimal

          dynamodb = boto3.resource('dynamodb')
          s3 = boto3.client('s3')

          def handler(event, context):
              try:
                  table_name = event.get('table_name', 'prp-db-org-policy')
                  bucket_name = event.get('bucket_name', 'grd-pol')
                  table = dynamodb.Table(table_name)

                  # List policy files in S3 bucket (policies/ folder)
                  response = s3.list_objects_v2(Bucket=bucket_name, Prefix='policies/')
                  if 'Contents' not in response:
                      return {'statusCode': 200, 'body': 'No policy files found.'}

                  for obj in response['Contents']:
                      key = obj['Key']
                      if not key.endswith('.json'):
                          continue

                      # Read policy file
                      policy_obj = s3.get_object(Bucket=bucket_name, Key=key)
                      policy_data = json.loads(policy_obj['Body'].read().decode('utf-8'))
                      service_name = key.split('/')[-1].replace('.json', '')

                      # Query DynamoDB for latest version
                      response = table.query(
                          KeyConditionExpression='services = :s',
                          ExpressionAttributeValues={':s': service_name},
                          ScanIndexForward=False,
                          Limit=1
                      )
                      latest_version = 'v0'
                      if response.get('Items'):
                          latest_version = response['Items'][0]['version']
                          # Increment version (e.g., v1 -> v2)
                          version_num = int(latest_version.replace('v', '')) + 1
                          new_version = f'v{version_num}'
                      else:
                          new_version = 'v1'

                      # Insert new item
                      table.put_item(
                          Item={
                              'services': service_name,
                              'version': new_version,
                              'approved_policy_actions': {
                                  'Version': policy_data['Version'],
                                  'Statement': policy_data['Statement']
                              }
                          }
                      )

                  return {'statusCode': 200, 'body': 'Policies updated successfully.'}
              except Exception as e:
                  return {'statusCode': 500, 'body': f'Error: {str(e)}'}
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          BUCKET_NAME: !Ref BucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GuardrailPolicyUpdateRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GuardrailPolicyUpdate:*

  PolicyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LambdaArn:
    Description: ARN of the policy update Lambda function
    Value: !GetAtt PolicyUpdateLambda.Arn
  BucketName:
    Description: Name of the S3 bucket for policy files
    Value: !Ref BucketName