AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Lambda function and S3 bucket to update prp-db-org-policy DynamoDB table with policies from aws-guardrail-policy-security repo.

Parameters:
  TableName:
    Type: String
    Default: prp-db-org-policy
    Description: Name of the DynamoDB table to store policies.
  BucketName:
    Type: String
    Default: grd-pol-123456789012  # Replace with your AWS account ID
    Description: Name of the S3 bucket to store policy files (must be 3-63 characters).

Resources:
  PolicyUpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GuardrailPolicyUpdate
      Handler: index.handler
      Runtime: python3.11
      Timeout: 300
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          from botocore.exceptions import ClientError

          # Initialize AWS clients
          dynamodb = boto3.resource('dynamodb')
          s3 = boto3.client('s3')

          def check_dynamodb_table_exists(table_name):
              try:
                  dynamodb.meta.client.describe_table(TableName=table_name)
              except ClientError as e:
                  if e.response['Error']['Code'] == 'ResourceNotFoundException':
                      raise ValueError(f"DynamoDB table '{table_name}' does not exist in the account.")
                  raise

          def extract_service_from_actions(policy_data):
              statements = policy_data.get('Statement', [])
              if not statements:
                  raise ValueError("Policy has no 'Statement' field.")
              for statement in statements:
                  actions = statement.get('Action', [])
                  if isinstance(actions, str):
                      actions = [actions]
                  elif not isinstance(actions, list):
                      continue
                  for action in actions:
                      if ':' in action and action != '*':
                          service = action.split(':')[0].lower()
                          if service:
                              return service
              raise ValueError("No valid service name found in policy actions.")

          def handler(event, context):
              try:
                  table_name = event.get('table_name', 'prp-db-org-policy')
                  bucket_name = event.get('bucket_name', 'grd-pol-123456789012')  # Default to fixed bucket
                  check_dynamodb_table_exists(table_name)
                  table = dynamodb.Table(table_name)
                  response = s3.list_objects_v2(Bucket=bucket_name, Prefix='policies/')
                  if 'Contents' not in response:
                      return {
                          'statusCode': 200,
                          'body': f'No policy files found in s3://{bucket_name}/policies/.'
                      }
                  for obj in response['Contents']:
                      key = obj['Key']
                      if not key.endswith('.json'):
                          continue
                      policy_obj = s3.get_object(Bucket=bucket_name, Key=key)
                      policy_data = json.loads(policy_obj['Body'].read().decode('utf-8'))
                      service_name = extract_service_from_actions(policy_data)
                      response = table.query(
                          KeyConditionExpression='services = :s',
                          ExpressionAttributeValues={':s': service_name},
                          ScanIndexForward=False,
                          Limit=1
                      )
                      latest_version = 'v0'
                      if response.get('Items'):
                          latest_version = response['Items'][0]['version']
                          version_num = int(latest_version.replace('v', '')) + 1
                          new_version = f'v{version_num}'
                      else:
                          new_version = 'v1'
                      table.put_item(
                          Item={
                              'services': service_name,
                              'version': new_version,
                              'approved_policy_actions': {
                                  'Version': policy_data['Version'],
                                  'Statement': policy_data['Statement']
                              }
                          }
                      )
                  return {
                      'statusCode': 200,
                      'body': f'Policies updated successfully in DynamoDB table {table_name}.'
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'body': f'Error updating policies: {str(e)}'
                  }
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          BUCKET_NAME: !Ref BucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GuardrailPolicyUpdateRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GuardrailPolicyUpdate:*

  PolicyBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LambdaArn:
    Description: ARN of the policy update Lambda function
    Value: !GetAtt PolicyUpdateLambda.Arn
  BucketName:
    Description: Name of the S3 bucket for policy files
    Value: !Ref BucketName