name: Setup Environment
description: Configures Python and AWS credentials for Guardrail workflows
inputs:
  gha-trust-role:
    description: IAM role for OIDC authentication
    required: true
  gha-cicd-role:
    description: IAM role for CI/CD operations
    required: true
  aws-region:
    description: AWS region for deployment
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install AWS CLI
      run: |
        python -m pip install --upgrade pip
        pip install -i https://artifactory.internal.cba/api/pypi/org.python.pypi/simple/ --upgrade awscli
      shell: bash
    - name: Assume OIDC Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.gha-trust-role }}
        role-session-name: GitHubActions
        aws-region: ${{ inputs.aws-region }}
    - name: Assume CI/CD Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.gha-cicd-role }}
        role-session-name: GitHubActions
        aws-region: ${{ inputs.aws-region }}
        role-chaining: true
