AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a DynamoDB table (prp-db-org-policy) with sort key versioning, enhanced GSI for approved_policy_actions scalability, AWS Backup with 90-day retention, and backup role name parameter

Parameters:
  TableName:
    Type: String
    Default: prp-db-org-policy
    Description: Name of the DynamoDB table
  BackupVaultName:
    Type: String
    Default: prp-OrgPolicy-BackupVault
    Description: Name of the AWS Backup vault
  BackupPlanName:
    Type: String
    Default: prp-orgpolicy-BackupPlan
    Description: Name of the AWS Backup plan
  BackupRoleName:
    Type: String
    Default: PrpOrgPolicyBackupRole
    Description: Name of the IAM role for AWS Backup

Resources:
  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: services
          AttributeType: S
        - AttributeName: version
          AttributeType: S
        - AttributeName: "approved_policy_actions.Statement[0].Effect"
          AttributeType: S
      KeySchema:
        - AttributeName: services
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: PolicyEffectIndex
          KeySchema:
            - AttributeName: services
              KeyType: HASH
            - AttributeName: "approved_policy_actions.Statement[0].Effect"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Ref BackupVaultName

  BackupPlan:
    Type: AWS::Backup::BackupPlan
    DependsOn: BackupVault
    Properties:
      BackupPlan:
        BackupPlanName: !Ref BackupPlanName
        BackupPlanRule:
          - RuleName: DailyBackup90DayRetention
            TargetBackupVault: !Ref BackupVaultName
            ScheduleExpression: cron(0 5 ? * * *)
            StartWindowMinutes: 60
            CompletionWindowMinutes: 180
            Lifecycle:
              DeleteAfterDays: 90

  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref BackupRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBBackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:ExportTableToPointInTime
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeBackup
                  - dynamodb:CreateBackup
                Resource: !GetAtt ServicesTable.Arn
              - Effect: Allow
                Action:
                  - backup:StartBackupJob
                  - backup:DescribeBackupVault
                  - backup:GetBackupVaultNotifications
                  - backup:PutBackupVaultNotifications
                  - backup:PutBackupVaultAccessPolicy
                  - backup:GetBackupVaultAccessPolicy
                Resource: !Sub "arn:aws:backup:${AWS::Region}:${AWS::AccountId}:backup-vault:${BackupVaultName}"
              - Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                Resource: '*'

  BackupSelection:
    Type: AWS::Backup::BackupSelection
    DependsOn: BackupPlan
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: ServicesTableBackupSelection
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources:
          - !GetAtt ServicesTable.Arn

Outputs:
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt ServicesTable.Arn
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref TableName
  StreamArn:
    Description: ARN of the DynamoDB stream
    Value: !GetAtt ServicesTable.StreamArn
  BackupVaultArn:
    Description: ARN of the AWS Backup vault
    Value: !Sub "arn:aws:backup:${AWS::Region}:${AWS::AccountId}:backup-vault:${BackupVaultName}"
  BackupPlanArn:
    Description: ARN of AWS Backup plan
    Value: !Sub "arn:aws:backup:${AWS::Region}:${AWS::AccountId}:backup-plan:${BackupPlanName}"
  BackupRoleArn:
    Description: ARN of the AWS Backup role
    Value: !GetAtt BackupRole.Arn