env:
  AWS_REGION: "ap-southeast-2" 

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is for repo checkout

jobs:
  example:
    runs-on: default
    environment: <environment>
    steps:
      - name: Configure AWS credentials (AssumeRoleWithWebIdentity)
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: "arn:aws:iam::<account id>:role/GHA-Trust"
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}
      - name: Configure AWS credentials (AssumeRole)
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: "arn:aws:iam::<account id>:role/GHA-CICD"
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
      
      # Example AWS request
      - name: get-caller-identity
        run: aws sts get-caller-identity
