AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the prp-db-org-policy DynamoDB table for TARV2 centralized policy storage.

# Parameters define configurable inputs for the template
Parameters:
  TableName:
    Type: String
    Default: prp-db-org-policy
    Description: Name of the DynamoDB table to store policies.
  OrganizationId:
    Type: String
    Description: AWS Organization ID (e.g., o-xxxxxxxxxxxx) to restrict cross-account read access to organization principals.

# Resources define the AWS components to be created
Resources:
  # DynamoDB table to store organization policies
  OrgPolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName # Name of the table, defaults to prp-db-org-policy
      AttributeDefinitions:
        - AttributeName: services
          AttributeType: S # String type for the services partition key
      KeySchema:
        - AttributeName: services
          KeyType: HASH # Partition key for services (e.g., s3, acm)
      ProvisionedThroughput:
        ReadCapacityUnits: 5 # Read capacity for provisioned throughput
        WriteCapacityUnits: 5 # Write capacity for provisioned throughput
      BillingMode: PROVISIONED # Use provisioned billing mode
      # Resource-based policy for Lambda access
      ResourcePolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            # Policy for GuardrailPolicyUpdate Lambda in the deploying account
            - Effect: Allow
              Principal:
                AWS: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:GuardrailPolicyUpdate # Lambda ARN in this account
              Action:
                - dynamodb:GetItem # Allow read access to table items
                - dynamodb:UpdateItem # Allow updates to table items
                - dynamodb:DescribeTable # Allow table metadata access
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName} # Table ARN constructed manually
            # Policy for cross-account principals (e.g., pdp-lambda) in the organization
            - Effect: Allow
              Principal:
                AWS: '*' # Allow all AWS principals in the organization
              Action:
                - dynamodb:GetItem # Allow read access to table items
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName} # Table ARN constructed manually
              Condition:
                StringEquals:
                  aws:PrincipalOrgID: !Ref OrganizationId # Restrict to organization accounts

# Outputs provide information about created resources
Outputs:
  TableArn:
    Description: ARN of the prp-db-org-policy DynamoDB table
    Value: !GetAtt OrgPolicyTable.Arn
  TableName:
    Description: Name of the prp-db-org-policy DynamoDB table
    Value: !Ref TableName