AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the prp-db-org-policy DynamoDB table for TARV2 centralized policy storage.

Parameters:
  BackupRoleName:
    Type: String
    Default: prp-backup-role
    Description: Name of the IAM role for DynamoDB backups.

Resources:
  OrgPolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prp-db-org-policy
      AttributeDefinitions:
        - AttributeName: services
          AttributeType: S
      KeySchema:
        - AttributeName: services
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref BackupRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ddb-Backup-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:CreateBackup
                  - dynamodb:DescribeTable
                  - dynamodb:ExportTableToPointInTime
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:UpdateContinuousBackups
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/prp-db-org-policy
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::aws-dynamodb-backup-*
                  - arn:aws:s3:::aws-dynamodb-backup-*/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/dynamodb/*:*

  DynamoDBCrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynamoDBCrossAccountAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::*:root(should be within an organisation )
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBCrossAccountAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt OrgPolicyTable.Arn

Outputs:
  TableArn:
    Description: ARN of the prp-db-org-policy DynamoDB table
    Value: !GetAtt OrgPolicyTable.Arn
  TableName:
    Description: Name of the prp-db-org-policy DynamoDB table
    Value: !Ref OrgPolicyTable

  
