name: Deploy Centralised PRP DDB for TARV2

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: string
        default: dev
      python_version:
        description: Python version
        required: true
        type: string
        default: "3.11"
env:
  AWS_REGION: "ap-southeast-2"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is for repo checkout

jobs:
  build-test-deploy:
    runs-on: default
    environment: ${{ inputs.environment || github.ref_name }}

    strategy:
      matrix:
        template:
          - prp-ddb.yml
        account:
          - dev
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version || '3.11' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -i https://artifactory.internal.cba/api/pypi/org.python.pypi/simple/ --upgrade awscli
        shell: bash

      - name: Configure AWS credentials (AssumeRoleWithWebIdentity)
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.GHA_TRUST_ROLE_ARN }}
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials (AssumeRole)
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.GHA_CICD_ROLE_ARN }}
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true

      - name: Validate CloudFormation Template
        run: |
          echo "Validating template: ${{ matrix.template }}"
          aws cloudformation validate-template \
            --template-body file://cloudformation/${{ matrix.template }} \
            --region ${{ env.AWS_REGION }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          echo "Deploying stack for template: ${{ matrix.template }}"
          set +e
          STACK_NAME="tarv2-prp-ddb-stack"
          aws cloudformation deploy \
            --template-file cloudformation/${{ matrix.template }} \
            --stack-name $STACK_NAME \
            --parameter-overrides \
              BackupRoleName=PrpOrgPolicyBackupRole \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }} \
            --no-fail-on-empty-changeset
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Deployment failed, checking stack status..."
            if aws cloudformation describe-stacks --stack-name $STACK_NAME --region ${{ env.AWS_REGION }} > /dev/null 2>&1; then
              STACK_STATUS=$(aws cloudformation describe-stacks \
                --stack-name $STACK_NAME \
                --region ${{ env.AWS_REGION }} \
                --query 'Stacks[0].StackStatus' \
                --output text)
              echo "Stack status: $STACK_STATUS"
              if [[ "$STACK_STATUS" == "ROLLBACK_COMPLETE" || "$STACK_STATUS" == "UPDATE_ROLLBACK_COMPLETE" ]]; then
                echo "Stack is in $STACK_STATUS state. Exiting with failure."
                exit 1
              elif [[ "$STACK_STATUS" == "CREATE_COMPLETE" || "$STACK_STATUS" == "UPDATE_COMPLETE" ]]; then
                echo "Stack is already up to date or created. Continuing..."
              else
                echo "Unexpected stack status: $STACK_STATUS. Exiting with failure."
                exit $EXIT_CODE
              fi
            else
              echo "Stack does not exist or another error occurred. Exiting with failure."
              exit $EXIT_CODE
            fi
          fi
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Populate DynamoDB with Initial Data
        run: |
          echo "Inserting initial data into table: prp-db-org-policy"
          # Item: sample keyword with version v1
          aws dynamodb put-item \
            --table-name prp-db-org-policy \
            --item '{
                "services": {"S": "sample keyword"},
                "version": {"S": "v1"},
                "approved_policy_actions": {
                  "M": {
                    "Version": {"S": "2012-10-17"},
                    "Statement": {
                      "L": [{
                        "M": {
                          "Action": {
                            "L": [{"S": "test:sampledata"}]
                          },
                          "Resource": {"S": "*"},
                          "Effect": {"S": "Allow"}
                        }
                      }]
                    }
                  }
                }
              }' \
            --region ${{ env.AWS_REGION }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
