AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the OrgReferencePolicies DynamoDB table for TARV2 centralized policy storage.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
      - Label:
          default: Table Configuration
        Parameters:
          - TableName

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, nonprod, prod]
    Description: The deployment environment
  TableName:
    Type: String
    Default: OrgReferencePolicies
    Description: Base name of the DynamoDB table to store policies

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]

Resources:
  OrgPolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TableName}-${Environment}"
      AttributeDefinitions:
        - AttributeName: services
          AttributeType: S
        - AttributeName: version
          AttributeType: N
      KeySchema:
        - AttributeName: services
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: !If [IsProd, 10, 5]
        WriteCapacityUnits: !If [IsProd, 10, 5]
      ResourcePolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowLambdaAccess
              Effect: Allow
              Principal:
                AWS: !Sub arn:aws:iam::422719327444:role/GuardrailPolicyUpdateRole
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DescribeTable
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}-${Environment}
            - Sid: AllowOrg1Access
              Effect: Allow
              Principal:
                AWS: '*'
              Action:
                - dynamodb:GetItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}-${Environment}
              Condition:
                StringEquals:
                  aws:PrincipalOrgID: o-fvwvfa9my5
            - Sid: AllowOrg2Access
              Effect: Allow
              Principal:
                AWS: '*'
              Action:
                - dynamodb:GetItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}-${Environment}
              Condition:
                StringEquals:
                  aws:PrincipalOrgID: o-w4mbxaieqf

Outputs:
  TableArn:
    Description: ARN of the OrgReferencePolicies DynamoDB table
    Value: !GetAtt OrgPolicyTable.Arn
  TableName:
    Description: Name of the OrgReferencePolicies DynamoDB table
    Value: !Ref OrgPolicyTable
