AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the prp-db-org-policy DynamoDB table for TARV2 centralized policy storage.

Parameters:
  TableName:
    Type: String
    Default: prp-db-org-policy
    Description: Name of the DynamoDB table to store policies.
  OrganizationId:
    Type: String
    Description: AWS Organization ID (e.g., o-xxxxxxxxxxxx) for cross-account access.

Resources:
  OrgPolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: services
          AttributeType: S
      KeySchema:
        - AttributeName: services
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED

  DynamoDBCrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynamoDBCrossAccountAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrganizationId
      Policies:
        - PolicyName: DynamoDBCrossAccountAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt OrgPolicyTable.Arn

Outputs:
  TableArn:
    Description: ARN of the prp-db-org-policy DynamoDB table
    Value: !GetAtt OrgPolicyTable.Arn
  TableName:
    Description: Name of the prp-db-org-policy DynamoDB table
    Value: !Ref TableName
  CrossAccountRoleArn:
    Description: ARN of the cross-account access role
    Value: !GetAtt DynamoDBCrossAccountAccessRole.Arn